### ISSUE TITLE
Cannot install: error while installing pycurl

### ISSUE THREAD

**Issue by csolisr** [TomCasavant/SocialSync#2]
When attempting to run the application in a virtual environment as suggested, I end up with the following error:

```
Collecting pycurl==7.43.0.6
  Using cached pycurl-7.43.0.6.tar.gz (222 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [30 lines of output]
      /tmp/pip-install-361m3mwg/pycurl_a3591ab8fa1e4178b745152aaa27e079/setup.py:933: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        if LooseVersion(distutils.__version__) > LooseVersion("1.0.1"):
      /tmp/pip-install-361m3mwg/pycurl_a3591ab8fa1e4178b745152aaa27e079/setup.py:935: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        if LooseVersion(distutils.__version__) < LooseVersion("1.0.3"):
      Traceback (most recent call last):
        File "/tmp/pip-install-361m3mwg/pycurl_a3591ab8fa1e4178b745152aaa27e079/setup.py", line 236, in configure_unix
          p = subprocess.Popen((self.curl_config(), '--version'),
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3.11/subprocess.py", line 1024, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/usr/lib/python3.11/subprocess.py", line 1901, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      FileNotFoundError: [Errno 2] No such file or directory: 'curl-config'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-361m3mwg/pycurl_a3591ab8fa1e4178b745152aaa27e079/setup.py", line 988, in <module>
          ext = get_extension(sys.argv, split_extension_source=split_extension_source)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-361m3mwg/pycurl_a3591ab8fa1e4178b745152aaa27e079/setup.py", line 649, in get_extension
          ext_config = ExtensionConfiguration(argv)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-361m3mwg/pycurl_a3591ab8fa1e4178b745152aaa27e079/setup.py", line 101, in __init__
          self.configure()
        File "/tmp/pip-install-361m3mwg/pycurl_a3591ab8fa1e4178b745152aaa27e079/setup.py", line 241, in configure_unix
          raise ConfigurationError(msg)
      ConfigurationError: Could not run curl-config: [Errno 2] No such file or directory: 'curl-config'
      [end of output]
```

Running on Debian Stable.

**Comment by csolisr** [comment]
My current workaround:

- Edit `requirements.txt` to manually bump `pycurl` to the latest version (currently `7.45.3`)
- Continue as usual and hope this doesn't break

**Comment by csolisr** [comment]
Also found that `python-apt` somehow no longer exists on `pip`? I substituted it for `python-apt-binary==2.6.0`, hopefully it provides the library just precompiled

**Comment by csolisr** [comment]
What version of Python are you using? The next warning I got was for a non-existing `ufw` and now I'm not sure if `pyufw` is a proper substitute.

**Comment by TomCasavant** [comment]
Sorry, probably should have checked and added that to the README. It looks like I'm running it on 3.9 right now

**Comment by TomCasavant** [comment]
What python version are you running? I grabbed the latest one I already had on my system and got the requirements working for python3.12 if you want to re-pull the repository and use `pip install -r requirements312.txt` (temporary fix, not sure what I'll do long-term)

**Comment by csolisr** [comment]
> Sorry, probably should have checked and added that to the README. It looks like I'm running it on 3.9 right now

That might explain it, since I'm on Debian Stable. I fetched the new `requirements312.txt` file and now it does build properly.
